### ISSUE TITLE
Image filter

### ISSUE THREAD

**Issue by stefanleh** [int128/slack-docker#2]
Hi, i really like this project but am missing a filter mechanism for certain images. Im using jenkins with slaves which are docker-containers and are created for each jenkins run. Therefore i get a lot of messages in slack. Best regards, Stefan

**Comment by int128** [comment]
Added the filter feature. Please check README.
Thanks.

**Comment by stefanleh** [comment]
Hey, thank you for the effort! :+1:

**Comment by stefanleh** [comment]
Hi again, tried it with my jenkins docker slave image but still get messages in slack:

	docker run -d -e image_regexp='stefanlehmann/centos-jenkins-docker-slave:.*' -e webhook=MYWEBHOOKHERE -v /var/run/docker.sock:/var/run/docker.sock int128/slack-docker

Best regards,
Stefan

**Comment by int128** [comment]
Would you check if the image is latest? If not, pull the image from Docker Hub.

```
% docker pull int128/slack-docker
% docker images
REPOSITORY            TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
int128/slack-docker   latest              036dc75d08e0        22 hours ago        650.4 MB
```

Thanks.

**Comment by stefanleh** [comment]
Look like i've got the latest version:

	% docker images | grep slack
	int128/slack-docker        latest         036dc75d08e0      3 days ago       650.4 MB

Could you please try with:

	docker run -d -e image_regexp='stefanlehmann/centos-jenkins-docker-slave:.*' -e webhook=MYWEBHOOKHERE -v /var/run/docker.sock:/var/run/docker.sock int128/slack-docker

and

	docker run -it stefanlehmann/centos-jenkins-docker-slave bash

to see if its working for you?

Tnx in advance,
Stefan

**Comment by int128** [comment]
Got it. Would you try following arg? It __excludes__ the jenkins slave image.

```sh
-e image_regexp='^(?!stefanlehmann/centos-jenkins-docker-slave)'
```

Thanks.

**Comment by stefanleh** [comment]
Sorry for the long time without responding. Hope you had a good start into 2016.

I've tried your regex and its working like a charm.
Thank you very much for the feature and the help.

Best regards,
Stefan

**Comment by int128** [comment]
I'm happy to help.
